### PR TITLE
V7.0.0 Ammendments

### PR DESCRIPTION
**Pull request by bmhughes**
# Description

Final amendments prior to v7.0.0 release.

## Issues Resolved

- Test testing DHCPv6 on Github actions
- Documentation typos

## Check List

- [x] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by kitchen-porter** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please include a CHANGELOG entry.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by bmhughes** [comment]
Missed a couple of typos and whilst working on something completely unrelated I managed to work out that you can flip the `disable_ipv6` sysctl and add an ipv6 address to a non-ipv6 enabled docker network so we can test with kitchen on github actions.

**Comment by Xorima** [comment]
How did you manage to get this working in actions?

**Comment by bmhughes** [comment]
> 
> 
> How did you manage to get this working in actions?

Strangely you **can** assign an ipv6 address to an interface in a container on a non ipv6 enabled docker network with a bit of jiggery-pokery. Surprisingly `net.ipv6.conf.eth0.disable_ipv6` is the only thing stopping you manually assigning an ipv6 address with `ip -6 addr add`, so flip that first and you're away. It's surprised me because I swear I've looked at doing this before and been unsuccessful.

It won't have any external access but it's enough for kitchen where we just want an address available for the process to bind to.

**Comment by Xorima** [comment]
That's brilliant, really nice catch there!

Good enough for kitchen is good enough for me (Plus I am sure that github don't really want loads of temp dhcp servers running in the lans :D )

LGTM when you are happy

**Pull request merged**
