### PR TITLE
Use a platform helper in the libraries

### PR DESCRIPTION
**Pull request by tas50**
Simplify this code a tiny bit

Signed-off-by: Tim Smith <tsmith@chef.io>

### CODE REVIEW

**Comment by Xorima** [comment]
Can you look at the tailing ubuntu tests?

**Comment by tas50** [comment]
@Xorima I know nothing of how dhcpd is meant to work, but I think I fixed the issue here.

**Comment by bmhughes** [comment]
The configuration test user should be ran as root by default so it shouldn't make any difference, it's a better practise to run as the correct users though. It's a strange one as it's just Ubuntu 18.04 and it works for me locally at d68050f already.

**Comment by bmhughes** [comment]
Yeh, this is officially weird. I'm going to leave it for today as presently, I'm out of ideas. So far:

1. The override directory has exactly the same perms between Ubuntu and everything else (that works!).
2. This worked perfectly before with nothing changing in the cookbook that _should_ affect it.
3. **Locally, on docker and vagrant everything passes.**
4. First thought for this normally would be selinux but the dokken images don't have it.

Can someone else try it locally to make sure it's not something on my system? I doubt it is but worth double checking.

**Pull request merged**
